server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: datasource
    url: jdbc:mysql://192.168.219.129:3306/bilibili?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

minio:
  url: http://192.168.219.129:9000
  access-name: minioadmin
  secret-key: minioadmin

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.bilibili: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"


knife4j:
    enable: true
    openapi:
        title: Bilibili-视频服务接口文档
        description: "Bilibili-视频服务接口文档"
        email:
        concat:
        url: https://www.bilibili.com
        version: v1.0.0
        group:
            default:
                group-name: default
                api-rule: package
                api-rule-resources:
                    - com.bilibili.video.controller